version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: github.com/dyson/certman
    schedule:
      interval: "weekly"
    # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
