language: go
go:
  - 1.14.x
os:
  - linux
services:
  - docker
script:
  - make test
  - go build ./...
before_deploy:
  - curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh |
    bash -s -- -b "${GOPATH}/bin" ${SEIHON_VERSION}
  - seihon --version
  - |
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    fi
deploy:
  - provider: script
    skip_cleanup: true
    script:
      seihon publish --template ./build/tmpl.Dockerfile -v "${TRAVIS_TAG}" -v "latest"
      --image-name bakito/traefik-cert-extractor --dry-run=false
    on:
      tags: true
