name: docker-image

on:
  push:
    branches: master
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{github.event.release.tag_name }}
        id: docker_build_release
        uses: docker/build-push-action@v2
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: true
          tags: quay.io/bakito/traefik-cert-extractor:latest,quay.io/bakito/traefik-cert-extractor:${{ github.event.release.tag_name }},ghcr.io/bakito/traefik-cert-extractor:latest,ghcr.io/bakito/traefik-cert-extractor:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: VERSION=${{ github.event.release.tag_name }}

      - name: Build and push master
        id: docker_build_master
        uses: docker/build-push-action@v2
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: true
          tags: quay.io/bakito/traefik-cert-extractor:master,ghcr.io/bakito/traefik-cert-extractor:master
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: VERSION=master
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
