name: quay

on:
  push:
    branches: master
  release:
    types:
      - created

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/bakito/traefik-cert-extractor:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          buildArgs: VERSION=${{ github.event.release.tag_name }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
